# -*- coding: utf-8 -*-
"""Stock Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1obEqIh1-dvM1lFboBaDb09ckm963nlMh
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
import matplotlib.dates as mdates

SH_df = pd.read_excel('./000001.SZ.xlsx')
Iflytek_df = pd.read_excel('./002030.SZ.xlsx')
VisualChina_df = pd.read_excel('./000681.SZ.xlsx')
Moutai_df = pd.read_excel('./600519.SH.xlsx')
CITIC_df = pd.read_excel('./600300.SH.xlsx')

from datetime import datetime
df_dict = {"PingAnBank": SH_df, "Iflytek": Iflytek_df, "VisualChina": VisualChina_df, "Moutai": Moutai_df, "CITIC": CITIC_df}
n = 1
for name,df in df_dict.items():
    df = df.iloc[::-1]# sequentially
    df['trade_date'] = df['trade_date'].apply(lambda x:datetime.strptime(str(x),"%Y%m%d"))
    df['trade_date']=pd.to_datetime(df['trade_date'])
    df.info()
    sns.set()
    warnings.filterwarnings('ignore')
    plt.figure(figsize=(24, 14), dpi=100, num=4)
    # volume chart
    x = df['trade_date']
    y1 = df['vol']
    plt.plot(x, y1, color='r', label='volume nums', linewidth=2)
    plt.xlabel('trade_date', fontsize=10)
    plt.ylabel('volume', fontsize=10)
    plt.title('volume chart for '+name, fontsize=15)
    print('volume chart')
    plt.savefig(f'figure{n}.jpg')
    plt.show()
    n += 1
    # OHLC chart
    plt.figure(figsize=(24, 14), dpi=100, num=4)
    x = df['trade_date']
    plt.plot(x, df.loc[:, 'open'], label='open price', linewidth=2)
    plt.plot(x, df.loc[:, 'high'], label='high price', linewidth=2)
    plt.plot(x, df.loc[:, 'low'], label='low price', linewidth=2)
    plt.plot(x, df.loc[:, 'close'], label='close price', linewidth=2)
    plt.xlabel('date', fontsize=15)
    plt.ylabel('price/exchange', fontsize=15)
    plt.title('OHLC chart', fontsize=15)
    print('OHLC chart')
    plt.savefig(f'figure{n}.jpg')
    plt.show()
    n += 1